### ISSUE TITLE
Question about changelog

### ISSUE THREAD

**Issue by ApertureDevelopment** [Meachamp/gmodws#1]
Is there a way to also define the changes parameter like with gmpublish?
I am trying to setup a CI to use this and automaticaly push changes to the steam workshop

**Comment by Meachamp** [comment]
I can't test at the moment, but calling UpdatePublishedFileSetChangeDescription on the object returned by CreatePublishedFileUpdateRequest should do the trick. I've got to update offsets anyway, so I'll consider implementing it then.

**Comment by Meachamp** [comment]
Bam, done. Two months late, so I don't know if you still need this, but enjoy otherwise.
