### ISSUE TITLE
login with STEAM_PASSWORD does not seem to work (?)

### ISSUE THREAD

**Issue by Earu** [Meachamp/gmodws#10]
Hey,
So I've been trying to use gmodws to make a GitHub action unfortunately, it seems like gmodws has troubles connecting to Steam.
Heres the code calling gmodws (node.js):
```js
function publishGMA(accountName, accountPassword, workshopId, gmaPath, changes) {
	const gmodwsPath = path.resolve("gmodws");
	fs.chmodSync(gmodwsPath, 7777);

	exec.exec(gmodwsPath, [accountName, workshopId, path.resolve(gmaPath), changes], {
		env: {
			STEAM_PASSWORD: accountPassword, // necessary for gmodws to work
			PATH: process.env.PATH,
		}
	}).then((errCode) => setOutput(errCode))
	.catch(err => setFailed(err.message));
}
```

heres the gmodws output:
```
[command]/home/earu/GSW-action/gmodws *********** 1182471500 /home/earu/GSW-action/addon.gma
Loaded.
Starting debug output.
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/data/src/clientdll/steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
/data/src/clientdll/steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
IUGC: 0x55eaf896ef30
Set CCheckCallback
Setting Creds: ***********
Cached login credentials not available.
Trying logon state....
sh: 1: /home/earu/GSW-action/../ubuntu12_64/gldriverquery: not found
sh: 1: /home/earu/GSW-action/../ubuntu12_32/gldriverquery: not found
Login failed. Please check credentials and try again.
Exiting workitem thread
::error::The process '/home/earu/GSW-action/gmodws' failed with exit code 1

```

Note: I compiled gmodws myself, because the glibc version was too high for debian 9

**Comment by Meachamp** [comment]
Sorry for the late reply. Is cached login working for you? I have a successful test from three days ago, and I don't think anything has changed since then.

**Comment by Earu** [comment]
Hey, thanks for the reply!
I haven't tried cached login, how do I use it? 

Also for additional context I don't have SteamCMD running on my user, but would it become a problem is another user was running it? Is it a problem If I don't run it?

EDIT: While testing the Windows build I made (see https://github.com/Meachamp/gmodws/pull/11) I tested it with Steam running in the background and it would say that there are two IPC servers and just not work. When Steam isn't running there are other issues specifically in tiers1. If you have Discord maybe it would be easier to talk about it all on there?

Thanks in advance.

**Comment by Meachamp** [comment]
I don't have multiple accounts I can test with, but that may be the issue. I would suggest trying in a container or a VM and seeing if that works for you. You should be able to do it with or without SteamCMD. 
If you've run SteamCMD, it will try to use the cached credentials, otherwise it will fall back to a username and password. I've tested both. 

Regarding the IPC, I'm not really sure. I reverse engineered everything on linux, so I might've missed something important that's windows specific. I'll give the problem some thought and get back to you, but no promises on a solution right now.

**Comment by Earu** [comment]
So I just tried running the latest stable versions of ubuntu and node 12.22, and as a matter of fact I'm running into the same problem I had with the Windows build: 
![image](https://user-images.githubusercontent.com/20880060/125178123-05bc0a00-e1e2-11eb-8fbe-a58661b23e88.png)

I'm directly fetching the latest release from this repo and running it with the `STEAM_PASSWORD` env var.

Side-note: The process seems to hang forever when it fails(?)

**Comment by Earu** [comment]
Oh my god, I'm so sorry I just realized Steam had SteamGuard enabled still with my email despite me turning it off. It DOES in fact work (on linux)! 

Although yeah the process seems to hang still.
