### ISSUE TITLE
Item update failed (code 8)

### ISSUE THREAD

**Issue by vurvdev** [Meachamp/gmodws#14]
Got this error using STEAM_PASSWORD in github actions on v1.5 release
https://github.com/Vurv78/WebAudio/actions/runs/5367620705/jobs/9737925633

**Comment by vurvdev** [comment]
Ended up making my own solution: https://github.com/Vurv78/gmod-upload

**Comment by Meachamp** [comment]
This is mostly legacy, apart from ability to automate 2FA, so low priority. I have an updated version but have not had time to make it ready for release.
