### ISSUE TITLE
Login timing out

### ISSUE THREAD

**Issue by m0uka** [Meachamp/gmodws#3]
Hey, I was trying this out but I am stuck at the login process. It just keeps timing out. SteamCMD login works fine, the logged SteamID is correct too, but it times out.
I know it might not be related to this script, but do you have any idea why would it happen? This is my only option for uploading add-ons on Linux with CLI. Thanks!

**Comment by Meachamp** [comment]
Hey, glad to hear this project's helping you out. I've just went and uploaded a test workshop addon with the utility, and it's working just fine. 

I've ran into the issue you're describing before on other distros. It appears to be related to a weird interaction between the `steamclient` library and certain versions of the linux kernel. Can you tell me what distro and kernel you're running? You can get this information with `uname -a`.

**Comment by m0uka** [comment]
Thanks for the fast reply! Here's the info: Linux main-linux 5.0.0-1028-gcp #29-Ubuntu SMP Thu Dec 19 11:31:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Meachamp** [comment]
Okay, I think that's the problem. I've finally located the issue where I remember seeing this discussed, it's here: https://github.com/ValveSoftware/steam-for-linux/issues/6326#issuecomment-506124600

What I would recommend is upgrading your kernel to something greater than `5.1.14` and seeing if that helps. For reference the test machine I used is on `5.5.0` and it seems to be working there. 

And sorry in advance for the news. Having to upgrade the kernel to get this to work is a terrible solution, but I don't think it can be helped. It's Valve's issue and I suppose this is how they chose to fix it.

**Comment by m0uka** [comment]
Thank you very much for the help. I will try it and report back. Again thanks!

**Comment by m0uka** [comment]
Perfect! Works now, thank you so much!

**Comment by m0uka** [comment]
OK, so it worked for a moment, but then it suddenly stopped working. My kernel version is 5.3.0-1018-gcp. Might be caused because steamcmd doesn't cache the auth info correctly? This shows up when trying to login - `FAILED login with invalid cached credentials`. I am forced to login every time.

**Comment by Meachamp** [comment]
Yeah, something's wrong with steamCMD caching credentials. I don't get this on my end. Check permissions and make sure you can log in properly on steamCMD without entering your password.

**Comment by m0uka** [comment]
Will do. Closing because this is not related to your repository
