### ISSUE TITLE
Uploading does not work with new Steam UGC

### ISSUE THREAD

**Issue by m0uka** [Meachamp/gmodws#4]
Hey, sorry to create another issue.
GMod recently changed the workshop uploading, and it now uses UGC instead of IRemoteStorage.
I tested it with my old addons, and it works perfectly with them, but with newly uploaded ones it doesn't work.
I think you need to use the ISteamUGC interface. If you wouldn't want to update this repository, could you tell me where I could get the ISteamUGC interface, and the updated SteamEngine.h, so I can implement it myself?
Thanks for your help!

**Comment by Meachamp** [comment]
I can add support in for ISteamUGC soon. I personally didn't think I'd see the day where gmod implemented that API, otherwise I would have done it earlier.

**Comment by Meachamp** [comment]
UGC support is here, check the new readme and releases section for more info.
