### ISSUE TITLE
steamclient not present

### ISSUE THREAD

**Issue by ApertureDevelopment** [Meachamp/gmodws#5]
Hello,

I tried uploading a addon with GModWS by using a syntax like 
``~/gmod/gmodws/gmodws account 1234567 test.gma``

But I got a error saying that the steamclient is not present. Are you sure it doesnt matter where GModWS is?

**Comment by Meachamp** [comment]
It doesn't matter where gmodws is, but you need to make sure that the steamclient library is present in the same directory as it.

**Comment by ApertureDevelopment** [comment]
the steamclient.so is present in the same directory ( assuming you mean your Pre-Compiled one ), my assumption would be that it doesn't look from the path it is, but in the path it was executed

**Comment by ApertureDevelopment** [comment]
Well now that my script CDs into the directory, I don't get steamclient not present anymore, but this:
```
[16:11:08]W:	 [Step 3/3] CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
[16:11:08]W:	 [Step 3/3] /home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
[16:11:08] :	 [Step 3/3] Loaded.
[16:11:08] :	 [Step 3/3] Loaded Workshop Command!
[16:11:08] :	 [Step 3/3] /home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
[16:11:08]W:	 [Step 3/3] /home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
[16:11:08] :	 [Step 3/3] CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
[16:11:08]W:	 [Step 3/3] steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
[16:11:08] :	 [Step 3/3] /home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
[16:11:08]W:	 [Step 3/3] sh: 1: ./../ubuntu12_64/gldriverquery: not found
[16:11:08]W:	 [Step 3/3] CAppInfoCacheReadFromDiskThread took 105 milliseconds to initialize
[16:11:08]W:	 [Step 3/3] sh: 1: ./../ubuntu12_32/gldriverquery: not found
[16:11:09]W:	 [Step 3/3] userremotestorage.cpp (3292) : Assertion Failed: you're asking cloud about files before you've loaded the cache - it's going to lie to you
[16:11:09] :	 [Step 3/3] steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
[16:11:09] :	 [Step 3/3] Trying logon state....
[16:11:09] :	 [Step 3/3] Opted-in Controller Mask for AppId 0: 0
[16:11:09] :	 [Step 3/3] STEAMID 76561198090797684
[16:11:09] :	 [Step 3/3] Logged in.
[16:11:09] :	 [Step 3/3] Compressing file...
[16:11:09] :	 [Step 3/3] Successfully compressed file. CRC: 140679971
[16:11:09] :	 [Step 3/3] Attempting to send file ....
[16:11:09]W:	 [Step 3/3] sh: 1: ./../ubuntu12_64/vulkandriverquery: not found
[16:11:15] :	 [Step 3/3] ----PUBLISHING FINISHED----
[16:11:15]W:	 [Step 3/3] Segmentation fault
[16:11:15] :	 [Step 3/3] Process exited with code 0
```

**Comment by Meachamp** [comment]
Segmentation fault on file upload? That's certainly not something I've ever run into. I think it might be environment-related with the steamclient, but I'm not sure. You could try swapping the `steamclient.so` file with a fresh one from your steamcmd install and see if that helps.

**Comment by ApertureDevelopment** [comment]
Still doesn't work.

My enviroment:
**OS:** Debian 10 Buster x64
**User:** teamcity-agent ( non root ) 
**SteamCMD Path:** ``~/steamcmd/``
**GModWS path:** ``~/gmod/gmodws/``

**Comment by ApertureDevelopment** [comment]
are there any enviroment variables to be considered?

**Comment by Meachamp** [comment]
Environment variables shouldn't affect the program for the most part. 

I see `----PUBLISHING FINISHED----` in the output above. Have you modified gmodws is any way, or is that output from your build agent?

Does steamcmd work properly? Make sure you've installed `lib32gcc1`. You could also try running something like `workshop_create_legacy_item 4000 test_file` in steamcmd to ensure you actually can upload things.

**Comment by ApertureDevelopment** [comment]
Yes, thats my build agents output, I didn't modify GModWS.

Also I have never used that steamcmd command, I got this reply from it:
``ERROR! ClientRemoteStorage()->FileWrite failed (Invalid Parameter).``

Also lib32gcc1 is installed and up to date

**Comment by Meachamp** [comment]
You get that with an empty file, but it's probably not important at this point unless you really want check. 

Without a way to reproduce this issue on my end and attach a debugger to see what's going on, this is going to be difficult to solve. I've tested on debian buster before and had no issues, so we've almost exhausted the list of things I have that could be going wrong. Out of curiosity though, how big is the file that you're trying to upload? I suppose if it was big enough it's possible it could be crashing steam.

**Comment by ApertureDevelopment** [comment]
About 144kb XD

**Comment by ApertureDevelopment** [comment]
But this server was a Debian 8 server once, I upgraded it to 9 and then 10

**Comment by Meachamp** [comment]
This is a long shot, but I can give you a debug version of this binary to maybe shed some light on the issue, if you're willing to try it.

**Comment by ApertureDevelopment** [comment]
At this point, I am willing to try anything

**Comment by Meachamp** [comment]
Run a test upload with this and send the output back. 
[gmodws.zip](https://github.com/Meachamp/gmodws/files/4564933/gmodws.zip)

**Comment by ApertureDevelopment** [comment]
Looks like the same output
```
Loaded.
Loaded Workshop Command!
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
Failed to set thread dynamic priority: setpriority failed -1
Failed to set thread priority: set failed for priority 8
Failed to set thread priority: per-thread setup failed
Failed to set thread dynamic priority: setpriority failed -1
Failed to set thread priority: set failed for priority 8
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
Segmentation fault
```

**Comment by Meachamp** [comment]
This time it didn't even make to trying to login. Is that with the new or old steamclient library?

**Comment by ApertureDevelopment** [comment]
Thats with the current steamclient.so from the ``linux64`` folder. The one from the ``linux32`` folder errors with ``steamclient not present!``

**Comment by Meachamp** [comment]
Okay, so the vtables in the engine interface have changed. You'll have to use the steamclient version from this repo.

**Comment by ApertureDevelopment** [comment]
Here is the output:
```
Loaded.
Loaded Workshop Command!
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
sh: 1: /home/teamcity-agent/gmodws_test/../ubuntu12_64/gldriverquery: not found
CAppInfoCacheReadFromDiskThread took 148 milliseconds to initialize
Trying logon state....
Opted-in Controller Mask for AppId 0: 0
STEAMID 76561198090797684
sh: 1: /home/teamcity-agent/gmodws_test/../ubuntu12_32/gldriverquery: not found
Logged in.
Compressing file...
Successfully compressed file. CRC: 2008960853
Attempting to send file ....
Remote->FileDelete ptr: 0x7fa0220a5340
File name: 2008960853_.gma
Deleting file from cloud...
File name: 2008960853_.gma
Buffer base: 0x7fa01455f3a0
Buffer size: 0x4cbd
Buffer data sample: 0x5d
Writing new file to cloud...
userremotestorage.cpp (3292) : Assertion Failed: you're asking cloud about files before you've loaded the cache - it's going to lie to you
userremotestorage.cpp (3292) : Assertion Failed: you're asking cloud about files before you've loaded the cache - it's going to lie to you
File written to cloud successfully!
File Name: 2008960853_.gma
sh: 1: /home/teamcity-agent/gmodws_test/../ubuntu12_64/vulkandriverquery: not found
File Share completed successfully!
File update succeeded!
Commit completed successfully!
Segmentation fault
```

**Comment by Meachamp** [comment]
This time it made it all the way to the end. The segfault is just a dumb steamclient thing that happens when you exit too quickly. See if this build helps with the segfaulting for now. I'm going to try to do some more reverse engineering soon to fix this among other issues, but my priority is to at least have something usable for you in the mean time.

**Comment by Meachamp** [comment]
Hold on, there's an issue with the current build.

**Comment by Meachamp** [comment]
Okay, try this. 
[gmodws.zip](https://github.com/Meachamp/gmodws/files/4565069/gmodws.zip)

**Comment by ApertureDevelopment** [comment]
I tried two times, the first time it didn't upload anything to the addon, the second time it still didn't upload but the segmentation fault is also back:
```
Loaded.
Engine: 0x7f3b930247c0
Loaded Workshop Command!
Creating global user.
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
Getting utils.
Getting remote.
Getting user.
Run frame.
Setting creds.
sh: 1: /home/teamcity-agent/gmodws_test/../ubuntu12_64/gldriverquery: not found
CAppInfoCacheReadFromDiskThread took 148 milliseconds to initialize
Raising priority.
Opted-in Controller Mask for AppId 0: 0
Trying logon state....
STEAMID 76561198090797684
sh: 1: /home/teamcity-agent/gmodws_test/../ubuntu12_32/gldriverquery: not found
Logged in.
Compressing file...
Successfully compressed file. CRC: 2008960853
Attempting to send file ....
sh: 1: /home/teamcity-agent/gmodws_test/../ubuntu12_64/vulkandriverquery: not found
Remote->FileDelete ptr: 0x7f3b91dda340
File name: 2008960853_.gma
Deleting file from cloud...
File name: 2008960853_.gma
Buffer base: 0x7f3b845a3b00
Buffer size: 0x4cbd
Buffer data sample: 0x5d
Writing new file to cloud...
userremotestorage.cpp (3292) : Assertion Failed: you're asking cloud about files before you've loaded the cache - it's going to lie to you
userremotestorage.cpp (3292) : Assertion Failed: you're asking cloud about files before you've loaded the cache - it's going to lie to you
File written to cloud successfully!
File Name: 2008960853_.gma
File Share completed successfully!
File update succeeded!
Commit completed successfully!
Segmentation fault
```

**Comment by Meachamp** [comment]
Have you used the new gmpublish binary on your addon (or created your addon) after January, 2020? If so, that's why it's not updating. I need to reverse engineer and add support for the new upload mechanism at some point. 

As a stop-gap measure, you can create a legacy addon with `workshop_create_legacy_item 4000 non_empty_test_file` and then update it from gmodws. Just don't use gmpublish on it until I can get this fixed.

**Comment by ApertureDevelopment** [comment]
Ah dang, because it didn't work I just uploaded it using GMPublish, today was the planned big release of my addon

**Comment by Meachamp** [comment]
It's unfortunate. Apparently this changeover was known as far as 6 months ago, but nobody made an issue about it on this repo. I'll get a fix out, but in the mean time you'll either have to use the alternate method or discontinue use of this uploader for now.

**Comment by ApertureDevelopment** [comment]
It's alright, I will wait for GModWS, my only alternative would be using a windows server for the agent, but I honestly don't want to do that XD

**Comment by Meachamp** [comment]
Just thought I'd give you an update on this; I'm about halfway through getting UGC reversed and implemented. A working release is about a day or two out still, but I'll have something basic for testing soon.

**Comment by Meachamp** [comment]
Here's a debug release that should work with UGC. Let me know how it works for you. 
[debug_release.zip](https://github.com/Meachamp/gmodws/files/4569591/debug_release.zip)

**Comment by Meachamp** [comment]
UGC support is here, check the new readme and releases section for more info.

**Comment by ApertureDevelopment** [comment]
Thank you, and sorry for not being avaiable this weekend, I was busy with stuff and couldn't come online
