### ISSUE TITLE
Item Update Failed

### ISSUE THREAD

**Issue by ApertureDevelopment** [Meachamp/gmodws#7]
Here I am again, and since today ( well today I found out ) I am unable to update my workshop addon again, here is the gmodws log:
```
[17:42:49]	[Step 3/3] --------------------------------
[17:42:49]	[Step 3/3] PUBLISHING ADDON TO WORKSHOP
[17:42:49]	[Step 3/3] --------------------------------
[17:42:49]	[Step 3/3] Loaded.
[17:42:49]	[Step 3/3] CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
[17:42:49]	[Step 3/3] /data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
[17:42:49]	[Step 3/3] /data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
[17:42:49]	[Step 3/3] /data/src/clientdll/steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
[17:42:49]	[Step 3/3] /data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
[17:42:49]	[Step 3/3] Warning: failed to init SDL thread priority manager: SDL not found
[17:42:49]	[Step 3/3] Warning: failed to set thread priority: set failed for priority 8
[17:42:49]	[Step 3/3] Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
[17:42:49]	[Step 3/3] CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
[17:42:49]	[Step 3/3] /data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
[17:42:49]	[Step 3/3] sh: 1: /home/teamcity-agent/gmod/gmodws/../ubuntu12_64/gldriverquery: not found
[17:42:50]	[Step 3/3] CAppInfoCacheReadFromDiskThread took 174 milliseconds to initialize
[17:42:50]	[Step 3/3] /data/src/clientdll/steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
[17:42:50]	[Step 3/3] Loaded client id: <removed>
[17:42:50]	[Step 3/3] Listening for IPv4 broadcast on: 27036
[17:42:50]	[Step 3/3] Listening for connections on: 0.0.0.0:27036
[17:42:50]	[Step 3/3] Opted-in Controller Mask for AppId 0: 0
[17:42:50]	[Step 3/3] Trying logon state....
[17:42:50]	[Step 3/3] STEAMID:76561198090797684
[17:42:50]	[Step 3/3] sh: 1: /home/teamcity-agent/gmod/gmodws/../ubuntu12_32/gldriverquery: not found
[17:42:50]	[Step 3/3] Logged in.
[17:42:50]	[Step 3/3] Starting Item Update.
[17:42:50]	[Step 3/3] Setting Item Content.
[17:42:50]	[Step 3/3] Submitting item update.
[17:42:50]	[Step 3/3] 
[17:42:50]	[Step 3/3] Item update failed (Code 15)
[17:42:52]	[Step 3/3] Exiting workitem thread
[17:42:52]	[Step 3/3] ----PUBLISHING FINISHED----
[17:42:52]	[Step 3/3] Process exited with code 0
```

**Comment by Meachamp** [comment]
You're getting a `k_EResultAccessDenied` error. That usually happens if you don't own the addon you're trying to upload to. Check to make sure you have the workshop ID right and you can properly view it under your account.

**Comment by ApertureDevelopment** [comment]
I just checked, the workshop id is correct, and the SteamID in the log is mine

Edit: I also can properly view it under my account

**Comment by ApertureDevelopment** [comment]
Where do you see that error anyway?

**Comment by ApertureDevelopment** [comment]
So, I removed the steamcmd and the Steam folder, re-downloaded it again and logged into my steam account, but I am still unable to update that addon

**Comment by Meachamp** [comment]
The error code is just a member of the standard EResult struct. You can see what they mean here: https://partner.steamgames.com/doc/api/steam_api#EResult

I'd recommend checking to make sure you can upload an update with the normal gmpublish binary from the same machine just to make sure.

**Comment by Meachamp** [comment]
I can confirm that this is something occurring on your end only. Updates are still working fine with my tests.

**Comment by ApertureDevelopment** [comment]
Could this maybe be a result of a too long change message? because I download this whole message:
https://github.com/Aperture-Development/MSync-2/releases/tag/v1.2.0

and use that as update message

**Comment by Meachamp** [comment]
That doesn't seem to be the case. Just tested with a long change message and it pushed just fine. What you could try is downloading the latest release and setting the GMODWS_DEBUG environment variable before running the program. Give me the debug output it provides.

**Comment by ApertureDevelopment** [comment]
I also noticed that it takes ages after the "Item update failed" message to finish up, but well here is the log output with the latest release and the enviroment variable "GMODWS_DEBUG" set to exist ( but its empty ) 
```

Loaded.
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
sh: 1: /home/teamcity-agent/gmod/gmodws/../ubuntu12_64/gldriverquery: not found
Loaded client id: 12920401844921256712
Listening for IPv4 broadcast on: 27036
Listening for connections on: 0.0.0.0:27036
Trying logon state....
STEAMID:76561198090797684
CAppInfoCacheReadFromDiskThread took 105 milliseconds to initialize
Opted-in Controller Mask for AppId 0: 0
Logged in.
Starting Item Update.
Setting Item Content.
Submitting item update.

Item update failed (Code 15)
Segmentation fault
```

**Comment by Meachamp** [comment]
The segfault is interesting, but you'll need to set GMODWS_DEBUG to a non empty value. `true` or something like that should work.

**Comment by ApertureDevelopment** [comment]
```
Loaded.
Starting debug output.
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
steamp2pvoice.cpp (161) : Assertion Failed: s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
IUGC: 0xb9b2a0
Set CCheckCallback
Setting Creds: <I preffer not everyone knowing my login name>
sh: 1: /home/teamcity-agent/gmod/gmodws/../ubuntu12_64/gldriverquery: not found
Loaded client id: 12920401844921256712
Listening for IPv4 broadcast on: 27036
Listening for connections on: 0.0.0.0:27036
Trying logon state....
STEAMID:76561198090797684
CAppInfoCacheReadFromDiskThread took 110 milliseconds to initialize
Opted-in Controller Mask for AppId 0: 0
Logged in.
Starting Item Update.
Update handle: 587597371513143192
Absolute path: "/home/teamcity-agent/temp/buildTmp/msync2.gma"
Setting Item Content.
Submitting item update.
Call Result: 587597371513143192

pbFailed: 0
CallResultStatus: 1
m_eResult: 15
m_bUserNeedsToAcceptWorkshopLegalAgreement: 0
IsAPICallCompleted Result: 0
Item update failed (Code 15)
Segmentation fault
```

**Comment by Meachamp** [comment]
Everything looks perfectly fine, which is completely baffling. Here's a list of things you can try in order to help us get more perspective on the problem:

- Can you use gmod_ws to upload to a different workshop addon? Does it work?
- Can you use the default gmpublish binary to upload the problem addon? Does it work?
- Can you try uploading the problem addon by hand, with gmod_ws? Does it work? Include the parameters you used, excluding username if you don't want to post that.

**Comment by ApertureDevelopment** [comment]
1. No it didn't work
2. Yes, using GMPublish it works
3. I tried that, thats the command I used:
``./gmodws <removed> 1636008512 /home/teamcity-agent/temp/buildTmp/msync2.gma``

**Comment by ApertureDevelopment** [comment]
Also sorry for the late reply, I had a issue with lots of water running behind my closet

**Comment by ApertureDevelopment** [comment]
I tried to replace the steamclient.so with the current one of the SteamCMD, now it tells me that my cached credentials are not avaiable

**Comment by Meachamp** [comment]
I can try moving the binary to the latest version of steamclient, but I'll have to get back to you on that.

**Comment by Meachamp** [comment]
I've done some testing and was able to repeatedly reproduce the access denied error condition for a few minutes, but only once. I'm not sure what changed to where I can't get it to happen again. What I do know is it seems to stem from a change steam made to the licensing check, hinted by an `Upload workshop item failed, license check failed` message in the logs. I'm still investigating as to why this is the case.

I have a test build with an updated steamclient library that may work for you. Let me know. 

[compiled.zip](https://github.com/Meachamp/gmodws/files/4744470/compiled.zip)

**Comment by Meachamp** [comment]
Just to give you an update on what happened: Steam updated how license data is checked or stored, breaking compatibility with old builds of the steam client. Running a new client irreversibly updated the license data in your account, breaking support for old clients. I've since confirmed that updating the steam client version fixes this issue, and will be pushing a release to deal with it shortly.

**Comment by ApertureDevelopment** [comment]
I was able to upload 3 changes to my Test addon ( was testing the commit message ), but now I am again unable to upload anything, maybe its a spam prevention and I have to try again later, but I thought I might let you know

**Comment by ApertureDevelopment** [comment]
It works now, it seems that it actually was a spam limitation
